### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by JetLaggedJackal** [nagyrobi/home-assistant-custom-components-pfsense-gateways#5]
Hi, my pfSense is on https. If i use  http://pfSenseIP/status_gateways_json.php?key=pfsense I get routed to https but displayed with 503 error. if I use  https://pfSenseHOSTNAME/status_gateways_json.php?key=pfsense I get json output in the browser but not in HomeAssistant

**Comment by nagyrobi** [comment]
Check [this](https://github.com/nagyrobi/home-assistant-custom-components-pfsense-gateways/issues/4).

**Comment by JetLaggedJackal** [comment]
For the love of me, I couldn't get it to work.
changed sensor.py from
`resource = config.get(CONF_RESOURCE).format(host, key)`
to
`resource = "https://{0}/status_gateways_json.php?key={1}"`

Tried also changing `DEFAULT_RESOURCE = "http://{0}/status_gateways_json.php?key={1}"` to use https.
None of that gives me any result in HA. Since everything is on HAProxy tried going directly to routerIP:8433. Not even that helped and in the browser works perfectly. 
I tried HACS debug but didn't get any errors. Any advice? HA is running on RPi4.

**Comment by nagyrobi** [comment]
Don't use https. Useless and resource hungry on a protected private network, anyway.
